// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import (
	fiber "github.com/gofiber/fiber/v2"
	mock "github.com/stretchr/testify/mock"
)

// RootController is an autogenerated mock type for the RootController type
type RootController struct {
	mock.Mock
}

// Root provides a mock function with given fields: c
func (_m *RootController) Root(c *fiber.Ctx) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
